global using u8 = byte;
global using i8 = sbyte;
global using u16 = ushort;
global using i16 = short;
global using cycle = int;
global using FluentAssertions;
global using Xunit;
global using Mos6502.Application;
global using Mos6502.Domain.Entities;
global using Mos6502.Domain.Enums;
global using Mos6502.Domain.Objects;
