global using u8 = byte;
global using i8 = sbyte;
global using u16 = ushort;
global using i16 = short;
global using cycle = int;
global using FluentAssertions;
global using Xunit;
global using mos6502;
global using mos6502.src.Domain.Enums;
global using mos6502.src.Domain.Entities;
